export const styles = {
  container: {
    padding: '1rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    '@media (max-width: 600px)': {
      padding: '0.5rem',
      gap: '0.5rem',
    },
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    '@media (max-width: 600px)': {
      flexDirection: 'column',
      alignItems: 'flex-start',
      gap: '0.25rem',
    },
  },
  title: {
    fontSize: '1.125rem',
    fontWeight: '600',
  },
  mainButton: {
    width: '100%',
    padding: '0.75rem',
    borderRadius: '0.5rem',
    fontWeight: '500',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    '@media (max-width: 600px)': {
      padding: '0.5rem',
      fontSize: '0.95rem',
    },
  },
  secondaryButton: {
    padding: '0.5rem 1rem',
    borderRadius: '0.375rem',
    borderWidth: '2px',
    borderStyle: 'solid',
    transition: 'all 0.2s',
  },
  formContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    marginTop: '1rem',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  },
  label: {
    fontSize: '0.875rem',
    fontWeight: '500',
  },
  input: {
    width: '100%',
    padding: '0.5rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderRadius: '0.375rem',
    fontSize: '0.875rem',
  },
  textarea: {
    width: '100%',
    padding: '0.5rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderRadius: '0.375rem',
    fontSize: '0.875rem',
    minHeight: '4rem',
    resize: 'vertical',
  },
  buttonGroup: {
    display: 'flex',
    gap: '0.5rem',
    marginTop: '0.5rem',
  },
  submitButton: {
    flex: 1,
    padding: '0.5rem',
    borderRadius: '0.375rem',
    fontWeight: '500',
    transition: 'all 0.2s',
  },
  cancelButton: {
    flex: 1,
    padding: '0.5rem',
    borderRadius: '0.375rem',
    borderWidth: '2px',
    borderStyle: 'solid',
    transition: 'all 0.2s',
  },
  selectedPinInfo: {
    padding: '1rem',
    borderRadius: '0.5rem',
    marginTop: '1rem',
  },
  selectedPinTitle: {
    fontWeight: '600',
    marginBottom: '0.5rem',
  },
  selectedPinDetails: {
    fontSize: '0.875rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  },
}
