export const styles = {
  overlay: {
    position: 'fixed',
    inset: '0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: '50',
    backdropFilter: 'blur(4px)',
  },
  modal: {
    backgroundColor: 'white',
    borderRadius: '0.75rem',
    padding: '1.5rem',
    width: '24rem',
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  headerTitle: {
    fontSize: '1.125rem',
    fontWeight: '500',
  },
  closeButton: {
    padding: '0.25rem',
    borderRadius: '0.375rem',
    transition: 'background-color 0.2s',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    flex: '1',
  },
  formFields: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
  },
  label: {
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: '500',
    marginBottom: '0.25rem',
  },
  input: {
    width: '100%',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '0.875rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderRadius: '0.375rem',
    transition: 'all 0.2s',
  },
  participantsList: {
    display: 'flex',
    flexDirection: 'column',
    flex: '1',
    overflowY: 'auto',
  },
  participantsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    maxHeight: '15rem',
    overflowY: 'auto',
    paddingRight: '0.5rem',
  },
  participantItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '0.75rem',
    borderRadius: '0.5rem',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    borderWidth: '1px',
    borderStyle: 'solid',
  },
  userInfo: {
    flex: '1',
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  avatar: {
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '9999px',
    objectFit: 'cover',
    borderWidth: '2px',
    borderStyle: 'solid',
  },
  avatarPlaceholder: {
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '9999px',
    borderWidth: '2px',
    borderStyle: 'solid',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '500',
  },
  userText: {
    display: 'flex',
    flexDirection: 'column',
  },
  username: {
    fontWeight: '500',
  },
  userRole: {
    fontSize: '0.75rem',
  },
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '0.5rem',
    marginTop: '1.5rem',
    paddingTop: '1rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
  },
  cancelButton: {
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '0.875rem',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderRadius: '0.375rem',
    transition: 'background-color 0.2s',
  },
  createButton: {
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '0.875rem',
    borderRadius: '0.375rem',
    transition: 'background-color 0.2s',
  },
}
