export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    padding: '1rem',
  },
  header: {
    fontWeight: '500',
    marginBottom: '1rem',
  },
  userList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    overflowY: 'auto',
    flex: '1',
    paddingRight: '0.25rem',
  },
  userItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.75rem',
    borderRadius: '0.5rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    transition: 'background-color 0.2s',
  },
  userInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  avatarContainer: {
    position: 'relative',
  },
  avatarImage: {
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '9999px',
    objectFit: 'cover',
    borderWidth: '2px',
    borderStyle: 'solid',
  },
  avatarPlaceholder: {
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '9999px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '500',
    borderWidth: '2px',
    borderStyle: 'solid',
  },
  statusIndicator: {
    position: 'absolute',
    bottom: '0',
    right: '0',
    width: '0.75rem',
    height: '0.75rem',
    borderRadius: '9999px',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: 'white',
  },
  userDetails: {
    display: 'flex',
    flexDirection: 'column',
  },
  usernameContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  username: {
    fontWeight: '500',
  },
  statusBadge: isOnline => ({
    fontSize: '0.75rem',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    paddingTop: '0.125rem',
    paddingBottom: '0.125rem',
    borderRadius: '9999px',
  }),
  userRole: {
    fontSize: '0.75rem',
  },
  chatButton: isOnline => ({
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    borderRadius: '0.375rem',
    fontSize: '0.875rem',
    transition: 'background-color 0.2s',
    cursor: isOnline ? 'pointer' : 'not-allowed',
  }),
}
